# Generated by Django 4.1.1 on 2022-09-17 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers_quota', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='quota_status',
            field=models.CharField(choices=[('Open', 'Open'), ('Close', 'Close')], default='Open', max_length=10),
        ),
    ]
